import Head from 'next/head';
import Image from 'next/image';
import * as React from 'react';
import ReactDOM from 'react-dom';
import styles from '../styles/Home.module.css';
import Button from '@mui/material/Button';
import MediaCard from '../components/MediaCard/MediaCard';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Project Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Melshtastic!</a>
        </h1>
        <MediaCard></MediaCard>

        <Button variant="text">Text</Button>
        <Button variant="contained">Contained</Button>
        <Button variant="outlined">Outlined</Button>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
